name: PhytoChem
channels:
  - rdkit
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.7.9
  - rdkit=2020.09.1.0
  - pip:
    - django==3.1.2
    - beautifulsoup4==4.9.3
    - python-dotenv==0.15.0
    - django-utils-six==2.0
    - django-crispy-forms==1.10.0
    - psycopg2-2.8.6