# Generated by Django 3.1.2 on 2020-10-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=60)),
                ('Smiles', models.CharField(max_length=250)),
                ('Molecular_Formula', models.CharField(max_length=50)),
                ('Molecular_Weight', models.FloatField()),
                ('H_Bond_Acceptors', models.IntegerField()),
                ('H_Bond_Donors', models.IntegerField()),
                ('Molar_Refractivity', models.FloatField()),
                ('TPSA', models.FloatField()),
                ('ROMol', models.TextField(max_length=150000)),
            ],
        ),
    ]
