# Generated by Django 3.1.4 on 2021-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='Smiles',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
