# Generated by Django 3.1.4 on 2021-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210217_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='Smiles',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
    ]
