# Generated by Django 3.1.2 on 2021-05-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210528_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='CYP2C9_inhibitor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
