# Generated by Django 3.1.2 on 2021-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_compound_cyp2c9_inhibitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='Egan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Ghose',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Muegge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Veber',
            field=models.IntegerField(blank=True),
        ),
    ]
