# Generated by Django 3.1.2 on 2021-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210529_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='Arom_Heavy_Atoms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='BBB_permeant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Bioavailability_Score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Brenk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='CYP1A2_inhibitor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='CYP2C19_inhibitor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='CYP2C9_inhibitor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='CYP2D6_inhibitor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='CYP3A4_inhibitor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Egan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Fraction_Csp3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='GI_absorption',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Ghose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='H_Bond_Acceptors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='H_Bond_Donors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Heavy_Atoms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Leadlikeness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Lipinski',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Molar_Refractivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Molecular_Formula',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Molecular_Weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Molecule_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Muegge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='PAINS',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='P_gp_substrate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Rotatable_bonds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Synthetic_accessibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='TPSA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Veber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='iLOGP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
