# Generated by Django 3.1.2 on 2021-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210529_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='LogKp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
