# Generated by Django 3.1.2 on 2020-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('pub_link', models.URLField()),
                ('data_description', models.TextField(blank=True, max_length=500)),
                ('mendeley_data_link', models.URLField(blank=True)),
                ('file', models.FileField(upload_to='submittedFiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
