# Generated by Django 3.1.2 on 2020-11-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('plantName', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='submittedFiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
