# Generated by Django 3.1.2 on 2020-11-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_data', '0002_contribution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
