# Generated by Django 3.1.2 on 2020-11-22 17:00

import django.core.validators
from django.db import migrations, models
import core.utils.QueryHandler


class Migration(migrations.Migration):

    dependencies = [
        ('submit_data', '0003_contribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='file',
            field=models.FileField(upload_to='submittedFiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['sdf']), core.utils.QueryHandler.validate_sdf]),
        ),
    ]
